# Generated by Django 5.1.6 on 2025-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='type',
            field=models.CharField(choices=[('single', 'Μονό'), ('combo', 'Παρολί'), ('system', 'Σύστημα')], default='single', max_length=10),
        ),
    ]
